
# main menu 
[[main]]
  name = "Ã€ propos"
  pageRef = "./about/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "./blog/"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "./tags/"
  weight = 40

# social icon
[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "Tiktok"
  pre = "fab tiktok"
  url = "https://tiktok.com/@alofonksyone"
  weight = 20

[[social]]
  name = "Twitter"
  pre = "fab x-twitter"
  url = "https://twitter.com/@alofonksyone"
  weight = 20

[[social]]
  name = "Facebook"
  pre = "fab facebook"
  url = "https://facebook.com/@alofonksyone"
  weight = 20